name: Unit Test

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      identifier:
        required: true
        type: string
  pull_request:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ inputs.identifier || github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: "[${{ matrix.os }}] Unit Tests"
    strategy:
      fail-fast: false
      matrix:
        include:
          - scheme: AWSAppSyncEvents
            os: iOS
            sdk: iphonesimulator
            destination: platform=iOS Simulator,name=iPhone 16 Pro Max,OS=18.5
          - scheme: AWSAppSyncEvents
            os: macOS
            sdk: macosx
            destination: platform=macOS,arch=arm64
          - scheme: AWSAppSyncEvents
            os: tvOS
            sdk: appletvsimulator
            destination: platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=18.5

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false

      - name: ${{ matrix.os }}
        run: |
          xcodebuild test \
          -scheme ${{ matrix.scheme }} \
          -destination "${{ matrix.destination }}" \
          -sdk ${{ matrix.sdk }} \
          -only-testing:"${{ matrix.scheme }}Tests" | xcpretty --simple --color --report junit && exit ${PIPESTATUS[0]}